# Generated by Django 6.0.3 on 2026-03-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.class')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='teachers.subject')),
            ],
        ),
    ]
