# Generated by Django 6.0.3 on 2026-03-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('section_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.section')),
            ],
            options={
                'ordering': ('day_of_week', 'period'),
            },
        ),
    ]
