# Generated by Django 6.0.3 on 2026-03-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routine', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.period'),
        ),
        migrations.AlterUniqueTogether(
            name='classroutine',
            unique_together={('class_fk', 'section_fk', 'day_of_week', 'period')},
        ),
    ]
